theme: jekyll-theme-minimal
title: Portfolio
logo: /images/Sample%20Logo.PNG
description: I am an aspiring data scientist and incoming PhD student at Rice University. This is a collection of projects I have worked on that I feel are compelling and worth sharing.
