theme: jekyll-theme-minimal
logo: /images/Sample%20Logo.PNG
description: I am an aspiring data scientist and incoming PhD student at Rice University. I am excited about applications of statistics and tech, particularly data analytics and machine learning, to finance, earth science, and engineering.
